name: Deploy to Sakura VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          mkdir -p java_app/discord2html/src/main/resources
          echo "discord.auth=${DISCORD_TOKEN}" > java_app/discord2html/src/main/resources/secret.properties
          mvn -B package --file java_app/discord2html/pom.xml

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -o StrictHostKeyChecking=no \
            java_app/discord2html/target/*.jar \
            $VPS_USERNAME@$VPS_HOST:/opt/discord2html/
          ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST \
            'systemctl restart discord2html'
