name: Deploy to Sakura VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          mkdir -p java_app/discord2html/src/main/resources
          echo "discord.auth=${DISCORD_TOKEN}" > java_app/discord2html/src/main/resources/secret.properties
          mvn -B package --file java_app/discord2html/pom.xml

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: '22'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl restart discord2html
          